import type { Attribute, ClassId } from "./types";

export type ClassData = {
  id: ClassId;
  name: string;
  keyAttribute: Attribute | Attribute[];
  hpBase: number;
  mpPerLevel: number;
  fixedSkills: string[];
  chooseSkills: number;
  skillOptions: string[];
  proficiency: string;
  firstLevelAbility: string;
  needsChoice?: string;
};

const broadOptions = [
  "acrobacia",
  "adestramento",
  "atletismo",
  "atuacao",
  "cavalgar",
  "conhecimento",
  "cura",
  "diplomacia",
  "enganacao",
  "fortitude",
  "furtividade",
  "guerra",
  "iniciativa",
  "intimidacao",
  "intuicao",
  "investigacao",
  "ladinagem",
  "luta",
  "misticismo",
  "nobreza",
  "oficio",
  "percepcao",
  "pontaria",
  "religiao",
  "sobrevivencia",
  "vontade",
];

export const classes: ClassData[] = [
  {
    id: "barbaro",
    name: "Bárbaro",
    keyAttribute: "str",
    hpBase: 24,
    mpPerLevel: 3,
    fixedSkills: ["fortitude", "luta"],
    chooseSkills: 4,
    skillOptions: [
      "adestramento",
      "atletismo",
      "cavalgar",
      "iniciativa",
      "intimidacao",
      "oficio",
      "percepcao",
      "pontaria",
      "sobrevivencia",
      "vontade",
    ],
    proficiency: "Armas simples e marciais, armaduras leves e médias, escudos.",
    firstLevelAbility: "Fúria +2: gasta 2 PM para melhorar ataque e dano corpo a corpo.",
  },
  {
    id: "bardo",
    name: "Bardo",
    keyAttribute: "cha",
    hpBase: 12,
    mpPerLevel: 4,
    fixedSkills: ["atuacao", "reflexos"],
    chooseSkills: 6,
    skillOptions: broadOptions,
    proficiency: "Armas simples e marciais, armaduras leves e instrumentos.",
    firstLevelAbility: "Inspiração: usa PM para conceder bônus aos aliados.",
  },
  {
    id: "bucaneiro",
    name: "Bucaneiro",
    keyAttribute: "dex",
    hpBase: 16,
    mpPerLevel: 3,
    fixedSkills: ["reflexos"],
    chooseSkills: 4,
    skillOptions: broadOptions,
    proficiency: "Armas simples e marciais leves, armaduras leves.",
    firstLevelAbility: "Esquiva Sagaz: soma Carisma na Defesa sem armadura pesada.",
    needsChoice: "Escolha Luta ou Pontaria como perícia inicial.",
  },
  {
    id: "cacador",
    name: "Caçador",
    keyAttribute: ["str", "dex"],
    hpBase: 16,
    mpPerLevel: 4,
    fixedSkills: ["sobrevivencia"],
    chooseSkills: 6,
    skillOptions: broadOptions,
    proficiency: "Armas simples e marciais, armaduras leves e médias, escudos.",
    firstLevelAbility: "Inimigo Predileto: escolha um tipo de criatura.",
    needsChoice: "Escolha atributo-chave e Luta ou Pontaria.",
  },
  {
    id: "cavaleiro",
    name: "Cavaleiro",
    keyAttribute: "str",
    hpBase: 20,
    mpPerLevel: 3,
    fixedSkills: ["fortitude", "luta"],
    chooseSkills: 2,
    skillOptions: broadOptions,
    proficiency: "Armas simples e marciais, armaduras leves, médias e pesadas, escudos.",
    firstLevelAbility: "Juramento: escolha um voto que guie seus poderes.",
    needsChoice: "Informe um juramento.",
  },
  {
    id: "clerigo",
    name: "Clérigo",
    keyAttribute: "wis",
    hpBase: 16,
    mpPerLevel: 5,
    fixedSkills: ["religiao", "vontade"],
    chooseSkills: 2,
    skillOptions: broadOptions,
    proficiency: "Armas simples, todas as armaduras e escudos.",
    firstLevelAbility: "Devoto de um Santo: escolha um santo padroeiro.",
    needsChoice: "Informe um santo padroeiro.",
  },
  {
    id: "druida",
    name: "Druida",
    keyAttribute: "wis",
    hpBase: 16,
    mpPerLevel: 5,
    fixedSkills: ["sobrevivencia", "vontade"],
    chooseSkills: 2,
    skillOptions: broadOptions,
    proficiency: "Armas simples, armaduras leves e médias, escudos.",
    firstLevelAbility: "Companheiro Animal.",
  },
  {
    id: "ladino",
    name: "Ladino",
    keyAttribute: "dex",
    hpBase: 12,
    mpPerLevel: 3,
    fixedSkills: ["ladinagem", "reflexos"],
    chooseSkills: 8,
    skillOptions: broadOptions,
    proficiency: "Armas simples, armaduras leves.",
    firstLevelAbility: "Ataque Furtivo +1d6.",
  },
  {
    id: "mago",
    name: "Mago",
    keyAttribute: "int",
    hpBase: 8,
    mpPerLevel: 6,
    fixedSkills: ["misticismo", "vontade"],
    chooseSkills: 2,
    skillOptions: broadOptions,
    proficiency: "Armas simples. Magos começam sem armadura.",
    firstLevelAbility: "Tradição Arcana: escolha uma escola.",
    needsChoice: "Informe uma tradição arcana.",
  },
  {
    id: "nobre",
    name: "Nobre",
    keyAttribute: "cha",
    hpBase: 16,
    mpPerLevel: 4,
    fixedSkills: ["vontade"],
    chooseSkills: 4,
    skillOptions: broadOptions,
    proficiency: "Armas simples e marciais, armaduras leves e médias, escudos.",
    firstLevelAbility: "Presença Imponente.",
    needsChoice: "Escolha Diplomacia ou Intimidação.",
  },
  {
    id: "soldado",
    name: "Soldado",
    keyAttribute: ["str", "dex"],
    hpBase: 20,
    mpPerLevel: 3,
    fixedSkills: ["fortitude"],
    chooseSkills: 2,
    skillOptions: broadOptions,
    proficiency: "Armas simples e marciais, armaduras leves, médias e pesadas, escudos.",
    firstLevelAbility: "Treinamento Especial: escolha um poder de combate.",
    needsChoice: "Escolha atributo-chave e Luta ou Pontaria.",
  },
];

export const classById = Object.fromEntries(classes.map((klass) => [klass.id, klass])) as Record<
  ClassId,
  ClassData
>;
